# numpy的创建，属性，索引和切片、广播、计算等基本操作

1、 创建numpy数组

In [1]:
import numpy as np

In [13]:
#注意，numpy数组元素之间是空格，没有逗号
#一维数组
my_array = np.array([1,2,3,4,5])
#选择某个元素、数组的大小
print(my_array)
print(my_array[0])
print(my_array.shape)

[1 2 3 4 5]
1
(5,)


In [10]:
#二维数组
my_2d_array = np.zeros((2,3))
print(my_2d_array)
print(my_2d_array[1][1])
print(my_2d_array.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
0.0
(2, 3)


In [12]:
#其他的创建方式
array_1 = np.array([1,2,3,4])

array_2 = np.array((1,2,3,4)) #不仅是list数组，类list也可以

array_3 = np.arange(5)

array_4 = np.linspace(0,10,4)

print(array_1)
print(array_2)
print(array_3)
print(array_4)

[1 2 3 4]
[1 2 3 4]
[0 1 2 3 4]
[ 0.          3.33333333  6.66666667 10.        ]


In [2]:
#创建特殊的数组
array_zero = np.zeros((2,3)) #(2,3)大小的矩阵，值为0

array_one = np.ones((2,3))  #(2,3)大小的矩阵，值为1

array_const = np.full((2,3),7) #(2,3)大小的矩阵，值为7

array_eye = np.eye(2)   #创建单位矩阵

print(array_zero)
print(array_one)
print(array_const)
print(array_eye)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0.]
 [0. 1.]]


In [27]:
#numpy常见的属性
array_property = np.array([[1,2,3],[2,3,4]])
print(type(array_property)) #对象类型
print(array_property.dtype) #元素类型
print(array_property.shape) #数组的形状
print(array_property.size)  #元素个数
print(array_property.ndim)  #数组维数
print(array_property.itemsize) #单个元素占用的字节数（int32，4个字节）
print(array_property.nbytes) #所有元素占用的字节数（4*6=24）

<class 'numpy.ndarray'>
int32
(2, 3)
6
2
4
24


2、numpy数组的加减乘除

In [4]:
#加减乘除，平方，均为对应位置元素操作
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
sum = a + b    #等价 np.add(a,b)
difference = a - b  #等价 np.subtract(a,b)
product = a * b  #对应位置相乘   #等价 np.multiply(a,b)
quotient = a / b  #等价 np.divide(a,b)
square = a ** 2   #等价 np.sqrt(a)

print(sum)
print(difference)
print(product)
print(quotient)
print(square)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]


In [5]:
#如果矩阵相乘？
matrix_product = a.dot(b)
dot_1_array = np.array([1,2,3])
dot_2_array = np.array([4,5,6])
print(matrix_product)
print(dot_1_array.dot(dot_2_array))

[[19 22]
 [43 50]]
32


3、索引和切片

In [3]:
clip_matrix = np.array([[11,12,13,14,15],
                        [16,17,18,19,20],
                        [21,22,23,24,25],
                        [26,27,28,29,30],
                        [31,32,33,34,35]])
#选取某个元素,2行2列
print(clip_matrix[2][2])
print(clip_matrix[2,2])  #与clip_matrix[2][2]功能一样
#选取某一行
print(clip_matrix[2])
#进行多维度选择
print(clip_matrix[0,1:4]) #0行，1到4列（左闭右开）
print(clip_matrix[:,1:4]) #所有行，1到4列（左闭右开）
#更高级的元素选择
print(clip_matrix[:3:2,:]) #选择0到3行，间隔为2，所有列

#花式索引
indices = ([1,2],[2,4])
print(clip_matrix[indices]) #与clip_matrix[1][2]和clip_matrix[2][4]功能一样

#使用布尔索引
bool_array = np.array([-1,2,3,0])
indices = bool_array > 0
print(bool_array[indices])#选择大于0的值

#where索引
a = np.arange(0, 100, 10)
b = np.where(a < 50)  #返回下标,tuple形式
c = np.where(a >= 50)[0]
print(a)
print(b) # >>>(array([0, 1, 2, 3, 4]),)
print(a[b])
print(c) # >>>[5 6 7 8 9]
#二维where
d2_a = a.reshape((2,5))
print(d2_a)
print(np.where(d2_a<60)) #返回坐标，由于是二维的，每个数组代表一个维度

23
23
[21 22 23 24 25]
[12 13 14]
[[12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]
 [32 33 34]]
[[11 12 13 14 15]
 [21 22 23 24 25]]
[18 25]
[2 3]
[ 0 10 20 30 40 50 60 70 80 90]
(array([0, 1, 2, 3, 4], dtype=int64),)
[ 0 10 20 30 40]
[5 6 7 8 9]
[[ 0 10 20 30 40]
 [50 60 70 80 90]]
(array([0, 0, 0, 0, 0, 1], dtype=int64), array([0, 1, 2, 3, 4, 0], dtype=int64))


4、广播操作:
广播是一种强大的机制，它允许numpy在执行算术运算时使用不同形状的数组。通常，我们有一个较小的数组和一个较大的数组，我们希望多次使用较小的数组来对较大的数组执行一些操作。

In [24]:
#数组或者向量与标量
array_1 = np.array([1,2,3])
array_2 = np.array([[1,2],[3,4]])
scalar_1 = 3
scalar_bc_1 = array_1 + scalar_1  #每个元素均加上标量
scalar_bc_2 = array_2 + scalar_1
print(scalar_bc_1)
print(scalar_bc_2)

#数组或者向量与向量
array_3 = np.array([1,2,3])
array_4 = np.array([[1,2,3],[3,4,5],[5,6,7]])
vector_1 = np.array([1,2,3])
vector_bc_1 = array_3 + vector_1  #每个元素均加上标量
vector_bc_2 = array_4 + vector_1 #vector，扩展为[[1,2,3],[1,2,3],[1,2,3]]
print(vector_bc_1)
print(vector_bc_2)

#计算维度不同的向量,每个维度都从1扩展到最大值，即同一个维度，要么相同，要么其中一个维度为1
array_5 = np.array([1,2,4]) #(3,)
array_6 = np.array([1,2])   #(2,)

print(np.reshape(array_5,(3,1))*array_6)  #(3,1)->(3,2)*(3,2)<-(2,)
print(np.reshape(array_6,(2,1))*array_5)

[4 5 6]
[[4 5]
 [6 7]]
[2 4 6]
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]
[[1 2]
 [2 4]
 [4 8]]
[[1 2 4]
 [2 4 8]]


In [ ]:
举例1,图像rbg,是的像素值扩大三倍,则下面可以兼容
Image  (3d array): 256 x 256 x 3
Scale  (1d array):         3        #可以看作1x1x3
Result (3d array): 256 x 256 x 3

举例2,当比较的任何一个维度为1时,则使用另一个.换句话说,大小为1的维被拉伸或复制以匹配另一维.
在以下示例中.A和B数组都具有长度为1的轴,在broadcast操作期间将其扩展为更大的大小
A      (4d array): 8 x 1 x 6 x 1
B      (3d array):    7 x 1 x 5    #可以看作1x7x1x5
Result  (4d array):  8 x 7 x 6 x 5

例子3
A      (2d array):  5 x 4
B      (1d array):     1  #可以看作1x1，均扩展
Result   (2d array):  5 x 4

例子4不具有兼容性
A      (1d array):  3
B      (1d array):  4   
例子5不具有兼容性
A      (2d array):     2 x 1
B      (3d array):  8 x 4 x 3  

5、数组特殊运算符

In [8]:
op_array = np.arange(10)
print(op_array)
print(op_array.sum()) #求和
print(op_array.min()) #最小值
print(op_array.max()) #最大值
print(op_array.cumsum()) #累加 
#它将像sum()这样的每个元素相加，但是它首先将第一个元素和第二个元素相加，并将计算结果存储在一个列表中，
#然后将该结果添加到第三个元素中，然后再将该结果存储在一个列表中。这将对数组中的所有元素执行此操作，并返回作为列表的数组之和的运行总数。

#另外也可以求得每行，每列的值
op_2_array = np.array([[1,2],[3,4]])
print(op_2_array.sum(axis = 0))  #列求和
print(np.sum(op_2_array,axis=1)) #行求和

#转置操作
print(op_2_array.T)

[0 1 2 3 4 5 6 7 8 9]
45
0
9
[ 0  1  3  6 10 15 21 28 36 45]
[4 6]
[3 7]
[[1 3]
 [2 4]]
