# 练习题

In [1]:
import numpy as np

1、查看numpy 版本

In [4]:
print(np.__version__)

1.16.4


2、创建0到9的一维数组

In [5]:
vector = np.arange(10)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


3、创建一个全为true的布尔数组

In [8]:
vec_bool = np.full((2,2),True)
print(vec_bool)

vec_bool_1 = np.ones((2,3),dtype = bool)
print(vec_bool_1)

[[ True  True]
 [ True  True]]
[[ True  True  True]
 [ True  True  True]]


4、从arr中提取所有奇数

In [14]:
arr = np.arange(12)
oddNums =[x for x in arr if x%2 != 0]
print(oddNums)
print(arr[arr%2==1])

[1, 3, 5, 7, 9, 11]
[ 1  3  5  7  9 11]


5、将arr中的所有奇数替换为1

In [15]:
arr = np.arange(10)
arr[arr % 2 ==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6、将arr中的所有奇数替换为1，原数组不发生改变

In [18]:
#np.where(condition, x, y) 满足条件(condition)，输出x，不满足输出y。
arr = np.arange(10)
print(np.where(arr % 2 == 0,arr,-1))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


补充 where

In [60]:
#第一种用法：只给where()函数传递一个数组作为参数，返回其中非0元素的下标。
x = np.arange(10)
print(np.where(x))
y = np.array([[1,0,3],[4,5,0]])
print(np.where(y)) #非0元素下标分别为[0,0],[0,2],[1,0],[1,1],二维的返回用一个元组表示，一维代表行下标，一维代表列下标

#第二种用法：给where()函数传递一个包含True/False值的数组，返回该数组中True值的下标，结合numpy数组的关系运算，可以返回数组中符合特定条件的元素的下标。
x = np.arange(10)
print(np.where(x>4))
y = np.array([[1,0,3],[4,5,0]])
print(np.where(y>2))
#第三种用法：给where()函数传递一个条件数组和两个值或数组，对于条件数组中等价于True的位置，从第一个值或数组中取值进行替换，否则从第二个值或数组中取值进行替换
x = np.arange(10)
print(np.where(x%2==1,x,-x))#奇数不变，偶数变为相反数，且返回为改变之后的值
y = np.array([[1,0,3],[4,5,0]])
print(np.where(y,[30,40,50],[60,70,80]))#对于每行，大于1，替换对应的[30,40,50],反之替换[60,70,80]


(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)
(array([0, 0, 1, 1], dtype=int64), array([0, 2, 0, 1], dtype=int64))
(array([5, 6, 7, 8, 9], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([2, 0, 1], dtype=int64))
[ 0  1 -2  3 -4  5 -6  7 -8  9]
[[30 70 50]
 [30 40 80]]


7、将一维数组转换为2行的2维数组

In [22]:
arr = np.arange(12)
print(arr.reshape(2,-1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


8、垂直堆叠数组a和数组b

In [34]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)  #10个1

#方法一
print(np.concatenate([a,b],axis = 0))
#方法二
print(np.vstack([a,b]))
#方法三
print(np.r_[a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9、水平堆叠数组a和数组b

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)  #10个1

#方法一
print(np.concatenate([a,b],axis = 1))
#方法二
print(np.hstack([a,b]))
#方法三
print(np.c_[a,b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


10、创建以下模式而不使用硬编码。只使用numpy函数和下面的输入数组a

In [41]:
a = np.array([1,2,3])
aa = np.repeat(a,2)
bb = np.tile(a,3)
print(aa)
print(bb)
#在numpy中，一个列表虽然是横着表示的，但它是列向量。
print(np.r_[aa,bb])

[1 1 2 2 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 2 2 3 3 1 2 3 1 2 3 1 2 3]


补充tile和repeat

In [45]:
#tile的用法， tile() 函数，就是将原矩阵横向、纵向地复制
mat = np.array([[1,2], [3, 4]])
#横向和纵向，（m,n）m表示纵向，n表示横向
print(np.tile(mat,(2,4)))

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


In [52]:
#repeat，即每列或者每行复制的个数
mat = np.array([[1,2], [3, 4]])
#axis=None，时候就会flatten当前矩阵，实际上就是变成了一个向量
print(np.repeat(mat,2,axis=None))  

#axis=0,沿着y轴复制，实际上增加了行数
print(np.repeat(mat,2,axis=0))  

#axis=1,沿着x轴复制，实际上增加列数
print(np.repeat(mat,2,axis=1))

#repeats可以为一个数，也可以为一个矩阵,每个数字代表的每一列的复制个数
print(np.repeat(mat,[2,3],axis=1))
print(np.repeat(mat,[2,3],axis=0))

[1 1 2 2 3 3 4 4]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]
[[1 1 2 2]
 [3 3 4 4]]
[[1 1 2 2 2]
 [3 3 4 4 4]]
[[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


11、获取数组a和数组b之间的公共项。

In [4]:
#求得2个数组的公共项
com_a = np.array([1,2,3,2,3,4,3,4,5,6])
com_b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(com_a,com_b))

[2 4]


12、从数组a中删除数组b中的所有项。

In [5]:
com_a = np.array([1,2,3,2,3,4,3,4,5,6])
com_b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.setdiff1d(com_a,com_b))

[1 3 5 6]


13、获取a和b元素匹配的位置。

In [6]:
com_a = np.array([1,2,3,2,3,4,3,4,5,6])
com_b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(com_a == com_b))

(array([1, 3, 5, 7], dtype=int64),)


14、获取5到10之间的所有项目

In [12]:
#得到下标
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[np.where((a>=5) & (a <=10))])

[ 6  9 10]


15、函数向量化，即转换适用于两个标量的函数maxx，以处理两个数组

In [14]:
#使用vectorize使得向量标量，以此处理向量中的元素
def maxx(x,y):
    if x>y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx,otypes=[float])
com_a = np.array([1,2,3,2,3,4,3,4,5,6])
com_b = np.array([7,2,10,2,7,4,9,4,9,8])
print(pair_max(com_a,com_b))

[ 7.  2. 10.  2.  7.  4.  9.  4.  9.  8.]


16、交换数组中的列

In [17]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,[1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


17、交换数组中的行

In [18]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[[1,0,2],:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


18、反转数组中的行

In [12]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[::-1,:]) #::-1,表示从后面开始不断-1，即-1，-2，-3

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


19、反转数组中的列

In [13]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


20、创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数。

In [14]:
#第一种：前面整数+0-1的小数
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)
#第二种
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.038 8.236 5.294]
 [5.687 5.02  6.318]
 [7.509 6.586 5.148]
 [6.405 9.053 5.604]
 [6.078 8.256 7.109]]
[[9.833 5.027 6.234]
 [5.733 7.008 7.09 ]
 [9.697 5.691 5.075]
 [8.624 9.988 5.057]
 [7.953 5.148 5.173]]


21、如何在numpy数组中只打印小数点后三位

In [17]:
#第一种
rand_arr = np.random.random([5,3])
print(np.around(rand_arr,decimals=3))

#第二种
rand_arr1 = np.random.random((5,3))
print(rand_arr1)
np.set_printoptions(precision = 3)
print(rand_arr1)

[[0.764 0.749 0.013]
 [0.337 0.246 0.479]
 [0.333 0.547 0.79 ]
 [0.654 0.661 0.941]
 [0.846 0.095 0.203]]
[[0.524 0.771 0.986]
 [0.015 0.579 0.021]
 [0.915 0.92  0.566]
 [0.505 0.488 0.052]
 [0.969 0.062 0.919]]
[[0.524 0.771 0.986]
 [0.015 0.579 0.021]
 [0.915 0.92  0.566]
 [0.505 0.488 0.052]
 [0.969 0.062 0.919]]


22、通过e式科学记数法来打印rand_arr（如1e10）

In [22]:
#False使用科学计数法
np.set_printoptions(suppress = False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/100
print(rand_arr)

#使用小数
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[5.434e-03 2.784e-03 4.245e-03]
 [8.448e-03 4.719e-05 1.216e-03]
 [6.707e-03 8.259e-03 1.367e-03]]
[[0.005434 0.002784 0.004245]
 [0.008448 0.000047 0.001216]
 [0.006707 0.008259 0.001367]]


23、如何限制numpy数组输出中打印的项目数？

In [43]:
#超过阈值就缩写
np.set_printoptions(threshold=8)
b = np.arange(15)
print(b)

[ 0  1  2 ... 12 13 14]


24、如何打印完整的numpy数组而不截断

In [45]:
b = np.arange(15)
#设置为很大的数字
np.set_printoptions(threshold=10000)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


25、导入鸢尾属植物数据集，保持文本不变。

In [51]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#使用genfromtxt原格式读取数据
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


26、从前面问题中导入的一维鸢尾属植物数据集中提取文本列的物种。

In [59]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

species = np.array([row[4] for row in iris_1d])
print(species[:5])

(150,)
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


f:\win_tensorflow\install\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


27、通过省略鸢尾属植物数据集种类的文本字段，将一维鸢尾属植物数据集转换为二维数组iris_2d。

In [65]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
#把元组变为list
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


f:\win_tensorflow\install\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


28、求出鸢尾属植物萼片长度的平均值、中位数和标准差(第1列)

In [78]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#文本转为数值
irisf = iris[:,:1].astype(np.float)
print(np.mean(irisf),np.median(irisf),np.std(irisf))

5.843333333333334 5.8 0.8253012917851409


29、创建一种标准化形式的鸢尾属植物间隔长度，其值正好介于0和1之间，这样最小值为0，最大值为1

In [79]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# 归一化
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
# or 
S = (sepallength - Smin)/sepallength.ptp()  #ptp()就是Smax-Smin
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

30、计算sepallength的softmax分数。

In [84]:

f = np.array([123, 456, 789]) # 例子中有3个分类，每个评分的数值都很大
print(np.exp(f))
p = np.exp(f) / np.sum(np.exp(f))  # 不妙：数值问题，可能导致数值爆炸
print(p)

[2.619517e+053 1.092154e+198           inf]
[ 0.  0. nan]


f:\win_tensorflow\install\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
f:\win_tensorflow\install\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.
f:\win_tensorflow\install\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [87]:
#为了防止数值爆炸，数值减去一个最大值
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength -= np.max(sepallength)
p = np.exp(sepallength) /np.sum(np.exp(sepallength))
print(p)

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812